# Yahoo Finance

In [3]:
import requests as r
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
link='https://query1.finance.yahoo.com/v1/finance/screener?crumb=00%2Finl.UKdq&lang=en-US&region=US&formatted=true&corsDomain=finance.yahoo.com'

In [ ]:
headers='''accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7
cache-control: no-cache
content-length: 566
content-type: application/json
cookie: APID=UPd136432b-66b5-11eb-8c62-0291f2e222b6; B=1rmiql5g0u7kh&b=3&s=qm; A1=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A3=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A1S=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc&j=GDPR; GUC=AQABAgFgLT1g9UIgiASi; EuConsent=CPBtzigPBtzigAOACCENBACgAAAAAAAAACiQAAAAAAAA; thamba=2; cmp=v=18&t=1613658098&j=1
origin: https://finance.yahoo.com
pragma: no-cache
referer: https://finance.yahoo.com/most-active?count=25&offset=25
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36'''

In [ ]:
headers=dict(i.split(': ') for i in headers.split('\n'))

In [ ]:
payload='''{"offset":25,"size":25,"sortField":"dayvolume","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"or","operands":[{"operator":"EQ","operands":["region","us"]},{"operator":"EQ","operands":["region","fr"]},{"operator":"EQ","operands":["region","gb"]},{"operator":"EQ","operands":["region","de"]},{"operator":"EQ","operands":["region","cn"]},{"operator":"EQ","operands":["region","jp"]}]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]}]}]},"userId":"","userIdType":"guid"}'''

In [ ]:
resp=r.post(link, headers=headers,data=payload)

In [ ]:
resp

In [ ]:
resp.json

In [ ]:
data=resp.json()['finance']['result'][0]['quotes']

In [ ]:
data

In [ ]:
pd.DataFrame(data).info()

In [ ]:
pd.DataFrame(data)

In [ ]:
pd.json_normalize(data)

In [ ]:
df=DataFrame

In [ ]:
datas=pd.DataFrame()
for i in range(0,250,25):
    headers="""accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7
cache-control: no-cache
content-length: 566
content-type: application/json
cookie: APID=UPd136432b-66b5-11eb-8c62-0291f2e222b6; B=1rmiql5g0u7kh&b=3&s=qm; A1=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A3=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A1S=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc&j=GDPR; GUC=AQABAgFgLT1g9UIgiASi; EuConsent=CPBtzigPBtzigAOACCENBACgAAAAAAAAACiQAAAAAAAA; thamba=2; cmp=v=18&t=1613658098&j=1
origin: https://finance.yahoo.com
pragma: no-cache
referer: https://finance.yahoo.com/most-active?count=25&offset=25
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"""
    payload="""{"offset":"""+str(i)+""","size":25,"sortField":"dayvolume","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"or","operands":[{"operator":"EQ","operands":["region","us"]},{"operator":"EQ","operands":["region","fr"]},{"operator":"EQ","operands":["region","gb"]},{"operator":"EQ","operands":["region","de"]},{"operator":"EQ","operands":["region","cn"]},{"operator":"EQ","operands":["region","jp"]}]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]}]}]},"userId":"","userIdType":"guid"}"""
    headers= dict(i.split(': ') for i in headers.split('\n'))
    resp=r.post(link, headers=headers, data=payload)
    data=resp.json()['finance']['result'][0]['quotes']
    pd.DataFrame(data)
    datas.append(data)

In [ ]:
datas

In [ ]:
datas[0]

In [ ]:
df=pd.json_normalize(datas[0])
dffinal=pd.DataFrame(df)
print("dffinal = ", dffinal)
for i in range(len(datas)):
    df=pd.json_normalize(datas[i])
    df.info()
    print("en cours",i)
    df.append(dffinal)
    print("cest bon",dffinal.info())

In [ ]:
dffinal.info()

In [ ]:
pd.json_normalize(datas[5])

In [5]:
datas=pd.DataFrame()
for i in range(0,9125,25):
    headers="""accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7
cache-control: no-cache
content-length: 566
content-type: application/json
cookie: APID=UPd136432b-66b5-11eb-8c62-0291f2e222b6; B=1rmiql5g0u7kh&b=3&s=qm; A1=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A3=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A1S=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc&j=GDPR; GUC=AQABAgFgLT1g9UIgiASi; EuConsent=CPBtzigPBtzigAOACCENBACgAAAAAAAAACiQAAAAAAAA; thamba=2; cmp=v=18&t=1613658098&j=1
origin: https://finance.yahoo.com
pragma: no-cache
referer: https://finance.yahoo.com/most-active?count=25&offset=25
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"""
    payload="""{"offset":"""+str(i)+""","size":25,"sortField":"dayvolume","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"or","operands":[{"operator":"EQ","operands":["region","us"]},{"operator":"EQ","operands":["region","fr"]},{"operator":"EQ","operands":["region","gb"]},{"operator":"EQ","operands":["region","de"]},{"operator":"EQ","operands":["region","cn"]},{"operator":"EQ","operands":["region","jp"]}]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]}]}]},"userId":"","userIdType":"guid"}"""
    headers= dict(i.split(': ') for i in headers.split('\n'))
    resp=r.post(link, headers=headers, data=payload)
    data=resp.json()['finance']['result'][0]['quotes']
    pd.DataFrame(data)
    print(i," datas are scrapped")
    datas=datas.append(data)
    print("data appended")
print("Done!")

0  datas are scrapped
data appended
25  datas are scrapped
data appended
50  datas are scrapped
data appended
75  datas are scrapped
data appended
100  datas are scrapped
data appended
125  datas are scrapped
data appended
150  datas are scrapped
data appended
175  datas are scrapped
data appended
200  datas are scrapped
data appended
225  datas are scrapped
data appended
250  datas are scrapped
data appended
275  datas are scrapped
data appended
300  datas are scrapped
data appended
325  datas are scrapped
data appended
350  datas are scrapped
data appended
375  datas are scrapped
data appended
400  datas are scrapped
data appended
425  datas are scrapped
data appended
450  datas are scrapped
data appended
475  datas are scrapped
data appended
500  datas are scrapped
data appended
525  datas are scrapped
data appended
550  datas are scrapped
data appended
575  datas are scrapped
data appended
600  datas are scrapped
data appended
625  datas are scrapped
data appended
650  datas are scrapped
data appended
675  datas are scrapped
data appended
700  datas are scrapped
data appended
725  datas are scrapped
data appended
750  datas are scrapped
data appended
775  datas are scrapped
data appended
800  datas are scrapped
data appended
825  datas are scrapped
data appended
850  datas are scrapped
data appended
875  datas are scrapped
data appended
900  datas are scrapped
data appended
925  datas are scrapped
data appended
950  datas are scrapped
data appended
975  datas are scrapped
data appended
1000  datas are scrapped
data appended
1025  datas are scrapped
data appended
1050  datas are scrapped
data appended
1075  datas are scrapped
data appended
1100  datas are scrapped
data appended
1125  datas are scrapped
data appended
1150  datas are scrapped
data appended
1175  datas are scrapped
data appended
1200  datas are scrapped
data appended
1225  datas are scrapped
data appended
1250  datas are scrapped
data appended
1275  datas are scrapped
data appended
1300  datas are scrapped
data appended
1325  datas are scrapped
data appended
1350  datas are scrapped
data appended
1375  datas are scrapped
data appended
1400  datas are scrapped
data appended
1425  datas are scrapped
data appended
1450  datas are scrapped
data appended
1475  datas are scrapped
data appended
1500  datas are scrapped
data appended
1525  datas are scrapped
data appended
1550  datas are scrapped
data appended
1575  datas are scrapped
data appended
1600  datas are scrapped
data appended
1625  datas are scrapped
data appended
1650  datas are scrapped
data appended
1675  datas are scrapped
data appended
1700  datas are scrapped
data appended
1725  datas are scrapped
data appended
1750  datas are scrapped
data appended
1775  datas are scrapped
data appended
1800  datas are scrapped
data appended
1825  datas are scrapped
data appended
1850  datas are scrapped
data appended
1875  datas are scrapped
data appended
1900  datas are scrapped
data appended
1925  datas are scrapped
data appended
1950  datas are scrapped
data appended
1975  datas are scrapped
data appended
2000  datas are scrapped
data appended
2025  datas are scrapped
data appended
2050  datas are scrapped
data appended
2075  datas are scrapped
data appended
2100  datas are scrapped
data appended
2125  datas are scrapped
data appended
2150  datas are scrapped
data appended
2175  datas are scrapped
data appended
2200  datas are scrapped
data appended
2225  datas are scrapped
data appended
2250  datas are scrapped
data appended
2275  datas are scrapped
data appended
2300  datas are scrapped
data appended
2325  datas are scrapped
data appended
2350  datas are scrapped
data appended
2375  datas are scrapped
data appended
2400  datas are scrapped
data appended
2425  datas are scrapped
data appended
2450  datas are scrapped
data appended
2475  datas are scrapped
data appended
2500  datas are scrapped
data appended
2525  datas are scrapped
data appended
2550  datas are scrapped
data appended
2575  datas are scrapped
data appended
2600  datas are scrapped
data appended
2625  datas are scrapped
data appended
2650  datas are scrapped
data appended
2675  datas are scrapped
data appended
2700  datas are scrapped
data appended
2725  datas are scrapped
data appended
2750  datas are scrapped
data appended
2775  datas are scrapped
data appended
2800  datas are scrapped
data appended
2825  datas are scrapped
data appended
2850  datas are scrapped
data appended
2875  datas are scrapped
data appended
2900  datas are scrapped
data appended
2925  datas are scrapped
data appended
2950  datas are scrapped
data appended
2975  datas are scrapped
data appended
3000  datas are scrapped
data appended
3025  datas are scrapped
data appended
3050  datas are scrapped
data appended
3075  datas are scrapped
data appended
3100  datas are scrapped
data appended
3125  datas are scrapped
data appended
3150  datas are scrapped
data appended
3175  datas are scrapped
data appended
3200  datas are scrapped
data appended
3225  datas are scrapped
data appended
3250  datas are scrapped
data appended
3275  datas are scrapped
data appended
3300  datas are scrapped
data appended
3325  datas are scrapped
data appended
3350  datas are scrapped
data appended
3375  datas are scrapped
data appended
3400  datas are scrapped
data appended
3425  datas are scrapped
data appended
3450  datas are scrapped
data appended
3475  datas are scrapped
data appended
3500  datas are scrapped
data appended
3525  datas are scrapped
data appended
3550  datas are scrapped
data appended
3575  datas are scrapped
data appended
3600  datas are scrapped
data appended
3625  datas are scrapped
data appended
3650  datas are scrapped
data appended
3675  datas are scrapped
data appended
3700  datas are scrapped
data appended
3725  datas are scrapped
data appended
3750  datas are scrapped
data appended
3775  datas are scrapped
data appended
3800  datas are scrapped
data appended
3825  datas are scrapped
data appended
3850  datas are scrapped
data appended
3875  datas are scrapped
data appended
3900  datas are scrapped
data appended
3925  datas are scrapped
data appended
3950  datas are scrapped
data appended
3975  datas are scrapped
data appended
4000  datas are scrapped
data appended
4025  datas are scrapped
data appended
4050  datas are scrapped
data appended
4075  datas are scrapped
data appended
4100  datas are scrapped
data appended
4125  datas are scrapped
data appended
4150  datas are scrapped
data appended
4175  datas are scrapped
data appended
4200  datas are scrapped
data appended
4225  datas are scrapped
data appended
4250  datas are scrapped
data appended
4275  datas are scrapped
data appended
4300  datas are scrapped
data appended
4325  datas are scrapped
data appended
4350  datas are scrapped
data appended
4375  datas are scrapped
data appended
4400  datas are scrapped
data appended
4425  datas are scrapped
data appended
4450  datas are scrapped
data appended
4475  datas are scrapped
data appended
4500  datas are scrapped
data appended
4525  datas are scrapped
data appended
4550  datas are scrapped
data appended
4575  datas are scrapped
data appended
4600  datas are scrapped
data appended
4625  datas are scrapped
data appended
4650  datas are scrapped
data appended
4675  datas are scrapped
data appended
4700  datas are scrapped
data appended
4725  datas are scrapped
data appended
4750  datas are scrapped
data appended
4775  datas are scrapped
data appended
4800  datas are scrapped
data appended
4825  datas are scrapped
data appended
4850  datas are scrapped
data appended
4875  datas are scrapped
data appended
4900  datas are scrapped
data appended
4925  datas are scrapped
data appended
4950  datas are scrapped
data appended
4975  datas are scrapped
data appended
5000  datas are scrapped
data appended
5025  datas are scrapped
data appended
5050  datas are scrapped
data appended
5075  datas are scrapped
data appended
5100  datas are scrapped
data appended
5125  datas are scrapped
data appended
5150  datas are scrapped
data appended
5175  datas are scrapped
data appended
5200  datas are scrapped
data appended
5225  datas are scrapped
data appended
5250  datas are scrapped
data appended
5275  datas are scrapped

data appended
5300  datas are scrapped
data appended
5325  datas are scrapped
data appended
5350  datas are scrapped
data appended
5375  datas are scrapped
data appended
5400  datas are scrapped
data appended
5425  datas are scrapped
data appended
5450  datas are scrapped
data appended
5475  datas are scrapped
data appended
5500  datas are scrapped
data appended
5525  datas are scrapped
data appended
5550  datas are scrapped
data appended
5575  datas are scrapped
data appended
5600  datas are scrapped
data appended
5625  datas are scrapped
data appended
5650  datas are scrapped
data appended
5675  datas are scrapped
data appended
5700  datas are scrapped
data appended
5725  datas are scrapped
data appended
5750  datas are scrapped
data appended
5775  datas are scrapped
data appended
5800  datas are scrapped
data appended
5825  datas are scrapped
data appended
5850  datas are scrapped
data appended
5875  datas are scrapped
data appended
5900  datas are scrapped
data appended
5925  datas are scrapped
data appended
5950  datas are scrapped
data appended
5975  datas are scrapped
data appended
6000  datas are scrapped
data appended
6025  datas are scrapped
data appended
6050  datas are scrapped
data appended
6075  datas are scrapped
data appended
6100  datas are scrapped
data appended
6125  datas are scrapped
data appended
6150  datas are scrapped
data appended
6175  datas are scrapped
data appended
6200  datas are scrapped
data appended
6225  datas are scrapped
data appended
6250  datas are scrapped
data appended
6275  datas are scrapped
data appended
6300  datas are scrapped
data appended
6325  datas are scrapped
data appended
6350  datas are scrapped
data appended
6375  datas are scrapped
data appended
6400  datas are scrapped
data appended
6425  datas are scrapped
data appended
6450  datas are scrapped
data appended
6475  datas are scrapped
data appended
6500  datas are scrapped
data appended
6525  datas are scrapped
data appended
6550  datas are scrapped
data appended
6575  datas are scrapped
data appended
6600  datas are scrapped
data appended
6625  datas are scrapped
data appended
6650  datas are scrapped
data appended
6675  datas are scrapped
data appended
6700  datas are scrapped
data appended
6725  datas are scrapped
data appended
6750  datas are scrapped
data appended
6775  datas are scrapped
data appended
6800  datas are scrapped
data appended
6825  datas are scrapped
data appended
6850  datas are scrapped
data appended
6875  datas are scrapped
data appended
6900  datas are scrapped
data appended
6925  datas are scrapped
data appended
6950  datas are scrapped
data appended
6975  datas are scrapped
data appended
7000  datas are scrapped
data appended
7025  datas are scrapped
data appended
7050  datas are scrapped
data appended
7075  datas are scrapped
data appended
7100  datas are scrapped
data appended
7125  datas are scrapped
data appended
7150  datas are scrapped
data appended
7175  datas are scrapped
data appended
7200  datas are scrapped
data appended
7225  datas are scrapped
data appended
7250  datas are scrapped
data appended
7275  datas are scrapped
data appended
7300  datas are scrapped
data appended
7325  datas are scrapped
data appended
7350  datas are scrapped
data appended
7375  datas are scrapped
data appended
7400  datas are scrapped
data appended
7425  datas are scrapped
data appended
7450  datas are scrapped
data appended
7475  datas are scrapped
data appended
7500  datas are scrapped
data appended
7525  datas are scrapped
data appended
7550  datas are scrapped
data appended
7575  datas are scrapped
data appended
7600  datas are scrapped
data appended
7625  datas are scrapped
data appended
7650  datas are scrapped
data appended
7675  datas are scrapped
data appended
7700  datas are scrapped
data appended
7725  datas are scrapped
data appended
7750  datas are scrapped
data appended
7775  datas are scrapped
data appended
7800  datas are scrapped
data appended
7825  datas are scrapped
data appended
7850  datas are scrapped
data appended
7875  datas are scrapped
data appended
7900  datas are scrapped
data appended
7925  datas are scrapped
data appended
7950  datas are scrapped
data appended
7975  datas are scrapped
data appended
8000  datas are scrapped
data appended
8025  datas are scrapped
data appended
8050  datas are scrapped
data appended
8075  datas are scrapped
data appended
8100  datas are scrapped
data appended
8125  datas are scrapped
data appended
8150  datas are scrapped
data appended
8175  datas are scrapped
data appended
8200  datas are scrapped
data appended
8225  datas are scrapped
data appended
8250  datas are scrapped
data appended
8275  datas are scrapped
data appended
8300  datas are scrapped
data appended
8325  datas are scrapped
data appended
8350  datas are scrapped
data appended
8375  datas are scrapped
data appended
8400  datas are scrapped
data appended
8425  datas are scrapped
data appended
8450  datas are scrapped
data appended
8475  datas are scrapped
data appended
8500  datas are scrapped
data appended
8525  datas are scrapped
data appended
8550  datas are scrapped
data appended
8575  datas are scrapped
data appended
8600  datas are scrapped
data appended
8625  datas are scrapped
data appended
8650  datas are scrapped
data appended
8675  datas are scrapped
data appended
8700  datas are scrapped
data appended
8725  datas are scrapped
data appended
8750  datas are scrapped
data appended
8775  datas are scrapped
data appended
8800  datas are scrapped
data appended
8825  datas are scrapped
data appended
8850  datas are scrapped
data appended
8875  datas are scrapped
data appended
8900  datas are scrapped
data appended
8925  datas are scrapped
data appended
8950  datas are scrapped
data appended
8975  datas are scrapped
data appended
9000  datas are scrapped
data appended
9025  datas are scrapped
data appended
9050  datas are scrapped
data appended
9075  datas are scrapped
data appended
9100  datas are scrapped
data appended
Done!

In [4]:
datas.shape

(9100, 78)

In [ ]:
datas.iloc[:, 10:20]

In [7]:
datas

,symbol,twoHundredDayAverageChangePercent,fiftyTwoWeekLowChangePercent,language,regularMarketDayRange,earningsTimestampEnd,epsForward,regularMarketDayHigh,twoHundredDayAverageChange,twoHundredDayAverage,...,trailingAnnualDividendYield,epsTrailingTwelveMonths,priceToBook,trailingPE,prevName,nameChangeDate,dividendDate,ipoExpectedDate,newListingDate,underlyingSymbol
0,SNDL,"{'raw': 1.9650325, 'fmt': '196.50%'}","{'raw': 10.086956, 'fmt': '1,008.70%'}",en-US,"{'raw': '1.22 - 1.71', 'fmt': '1.22 - 1.71'}","{'raw': 1605177000, 'fmt': '2020-11-12', 'long...","{'raw': -0.44, 'fmt': '-0.44'}","{'raw': 1.71, 'fmt': '1.7100'}","{'raw': 1.0139854, 'fmt': '1.01'}","{'raw': 0.5160146, 'fmt': '0.52'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RMM.L,"{'raw': -0.3829714, 'fmt': '-38.30%'}","{'raw': 0.69154227, 'fmt': '69.15%'}",en-US,"{'raw': '0.305 - 0.3485', 'fmt': '0.31 - 0.35'}","{'raw': 1620993600, 'fmt': '2021-05-14', 'long...",NaN,"{'raw': 0.3485, 'fmt': '0.3485'}","{'raw': -0.21102795, 'fmt': '-0.21'}","{'raw': 0.55102795, 'fmt': '0.55'}",...,"{'raw': 0.022222223, 'fmt': '0.02%'}","{'raw': -1.1, 'fmt': '-1.1000'}","{'raw': 11.333334, 'fmt': '11.33'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VAST.L,"{'raw': -0.27283886, 'fmt': '-27.28%'}","{'raw': 0.18367347, 'fmt': '18.37%'}",en-US,"{'raw': '0.1113 - 0.1198', 'fmt': '0.11 - 0.12'}","{'raw': 1611745140, 'fmt': '2021-01-27', 'long...",NaN,"{'raw': 0.1198, 'fmt': '0.1198'}","{'raw': -0.043524474, 'fmt': '-0.04'}","{'raw': 0.15952447, 'fmt': '0.16'}",...,NaN,"{'raw': -0.1, 'fmt': '-0.1000'}","{'raw': 115.99999, 'fmt': '116.00'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002002.SZ,"{'raw': -0.03449859, 'fmt': '-3.45%'}","{'raw': 0.28571427, 'fmt': '28.57%'}",en-US,"{'raw': '3.34 - 3.57', 'fmt': '3.34 - 3.57'}","{'raw': 1619780340, 'fmt': '2021-04-30', 'long...","{'raw': 0.56, 'fmt': '0.56'}","{'raw': 3.57, 'fmt': '3.5700'}","{'raw': -0.12541676, 'fmt': '-0.13'}","{'raw': 3.6354167, 'fmt': '3.64'}",...,"{'raw': 0.017804155, 'fmt': '0.02%'}","{'raw': 0.282, 'fmt': '0.2820'}","{'raw': 1.17, 'fmt': '1.17'}","{'raw': 12.446808, 'fmt': '12.45'}",NaN,NaN,NaN,NaN,NaN,NaN
4,UJO.L,"{'raw': -0.12591688, 'fmt': '-12.59%'}","{'raw': 1.1333332, 'fmt': '113.33%'}",en-US,"{'raw': '0.155 - 0.1687', 'fmt': '0.16 - 0.17'}","{'raw': 1620993600, 'fmt': '2021-05-14', 'long...",NaN,"{'raw': 0.1687, 'fmt': '0.1687'}","{'raw': -0.023048952, 'fmt': '-0.02'}","{'raw': 0.18304895, 'fmt': '0.18'}",...,NaN,"{'raw': -0.0, 'fmt': '-0.0000'}","{'raw': 159.99998, 'fmt': '160.00'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,AGJ.F,"{'raw': 0.25333592, 'fmt': '25.33%'}","{'raw': 1.8490908, 'fmt': '184.91%'}",en-US,"{'raw': '94.02 - 94.02', 'fmt': '94.02 - 94.02'}",NaN,NaN,"{'raw': 94.02, 'fmt': '94.02'}","{'raw': 19.004196, 'fmt': '19.00'}","{'raw': 75.0158, 'fmt': '75.02'}",...,"{'raw': 0.006568144, 'fmt': '0.01%'}","{'raw': 5.65, 'fmt': '5.65'}","{'raw': 2.3631427, 'fmt': '2.36'}","{'raw': 16.640707, 'fmt': '16.64'}",NaN,NaN,NaN,NaN,NaN,NaN
21,TPD.F,"{'raw': 0.30135736, 'fmt': '30.14%'}","{'raw': 3.8727272, 'fmt': '387.27%'}",en-US,"{'raw': '26.8 - 26.8', 'fmt': '26.80 - 26.80'}",NaN,NaN,"{'raw': 26.8, 'fmt': '26.80'}","{'raw': 6.2061176, 'fmt': '6.21'}","{'raw': 20.593882, 'fmt': '20.59'}",...,NaN,"{'raw': 1.64, 'fmt': '1.64'}","{'raw': 10.903173, 'fmt': '10.90'}","{'raw': 16.341463, 'fmt': '16.34'}",NaN,NaN,NaN,NaN,NaN,NaN
22,AZD.F,"{'raw': -0.105956286, 'fmt': '-10.60%'}","{'raw': 2.1631784, 'fmt': '216.32%'}",en-US,"{'raw': '40.805 - 40.805', 'fmt': '40.81 - 40....",NaN,NaN,"{'raw': 40.805, 'fmt': '40.81'}","{'raw': -4.835945, 'fmt': '-4.84'}","{'raw': 45.640945, 'fmt': '45.64'}",...,"{'raw': 0.0038991105, 'fmt': '0.00%'}","{'raw': -3.102, 'fmt': '-3.10'}","{'raw': 1.6822642, 'fmt': '1.68'}",NaN,"Aaron's, Inc.",2021-02-20,NaN,NaN,NaN,NaN
23,QGJ.F,"{'raw': 0.32289365, 'fmt': '32.29%'}","{'raw': 1.9601228, 'fmt': '196.01%'}",en-US,"{'raw': '96.5 - 96.5', 'fmt': '96.50 - 96.50'}",NaN,NaN,"{'raw': 96.5, 'fmt': '96.50'}","{'raw': 23.553848, 'fmt': '23.55'}","{'raw': 72.94615, 'fmt': '72.95'}",...,"{'raw': 0.023857867, 'fmt': '0.02%'}","{'raw': 8.22, 'fmt': '8.22'}","{'raw': 4.0357995, 'fmt': '4.04'}","{'raw': 11.739659, 'fmt': '11.74'}",NaN,NaN,NaN,NaN,NaN,NaN
24,KKKUF,"{'raw': 0.2758555, 'fmt': '27.59%'}","{'raw': 1.2511356, 'fmt': '125.11%'}",en-US,"{'raw': '34.69 - 34.69', 'fmt': '34.69 - 34.69'}",NaN,NaN,"{'raw': 34.69, 'fmt': '34.69'}","{'raw': 7.5004005, 'fmt': '7.50'}","{'raw': 27.189598, 'fmt': '27.19'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
col1=datas.twoHundredDayAverageChangePercent
col1

0       {'raw': 1.9619548, 'fmt': '196.20%'}
1     {'raw': -0.38682732, 'fmt': '-38.68%'}
2      {'raw': -0.2749056, 'fmt': '-27.49%'}
3     {'raw': -0.035475068, 'fmt': '-3.55%'}
4     {'raw': -0.12928464, 'fmt': '-12.93%'}
                       ...
20      {'raw': 0.15341677, 'fmt': '15.34%'}
21      {'raw': 0.062395055, 'fmt': '6.24%'}
22      {'raw': 0.12193909, 'fmt': '12.19%'}
23      {'raw': 0.024003299, 'fmt': '2.40%'}
24     {'raw': -0.09493884, 'fmt': '-9.49%'}
Name: twoHundredDayAverageChangePercent, Length: 9100, dtype: object

In [8]:
datas.twoHundredDayAverageChangePercent.map(lambda x: x['raw'])

TypeError: 'float' object is not subscriptable

In [10]:
subset = datas['twoHundredDayAverageChangePercent'].copy()
mask = subset.isna()
subset.loc[~mask] = subset.loc[~mask].apply(lambda x: x.get('raw'))
datas['twoHundredDayAverageChangePercent'] = subset

In [97]:
datas.iloc[:, 70:80]

,priceToBook,trailingPE,prevName,nameChangeDate,dividendDate,ipoExpectedDate,newListingDate,underlyingSymbol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11.3333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.17,12.4468,NaN,NaN,NaN,NaN,NaN,NaN
4,160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
20,2.36314,16.6407,NaN,NaN,NaN,NaN,NaN,NaN
21,10.9032,16.3415,NaN,NaN,NaN,NaN,NaN,NaN
22,1.68226,NaN,"Aaron's, Inc.",2021-02-20,NaN,NaN,NaN,NaN
23,4.0358,11.7397,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
subset = datas['trailingAnnualDividendRate'].copy()
mask = subset.isna()
subset.loc[~mask] = subset.loc[~mask].apply(lambda x: x.get('raw'))
datas['trailingAnnualDividendRate'] = subset
datas

,symbol,twoHundredDayAverageChangePercent,fiftyTwoWeekLowChangePercent,language,regularMarketDayRange,earningsTimestampEnd,epsForward,regularMarketDayHigh,twoHundredDayAverageChange,twoHundredDayAverage,...,trailingAnnualDividendYield,epsTrailingTwelveMonths,priceToBook,trailingPE,prevName,nameChangeDate,dividendDate,ipoExpectedDate,newListingDate,underlyingSymbol
0,SNDL,1.96503,10.086956,en-US,1.22 - 1.71,1605177000,-0.44,1.7100,1.01399,0.516015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RMM.L,-0.382971,0.691542,en-US,0.305 - 0.3485,1620993600,NaN,0.3485,-0.211028,0.551028,...,0.0222222,-1.1,11.3333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VAST.L,-0.272839,0.183673,en-US,0.1113 - 0.1198,1611745140,NaN,0.1198,-0.0435245,0.159524,...,NaN,-0.1,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002002.SZ,-0.0344986,0.285714,en-US,3.34 - 3.57,1619780340,0.56,3.5700,-0.125417,3.63542,...,0.0178042,0.282,1.17,12.4468,NaN,NaN,NaN,NaN,NaN,NaN
4,UJO.L,-0.125917,1.133333,en-US,0.155 - 0.1687,1620993600,NaN,0.1687,-0.023049,0.183049,...,NaN,-0,160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,AGJ.F,0.253336,1.849091,en-US,94.02 - 94.02,NaN,NaN,94.0200,19.0042,75.0158,...,0.00656814,5.65,2.36314,16.6407,NaN,NaN,NaN,NaN,NaN,NaN
21,TPD.F,0.301357,3.872727,en-US,26.8 - 26.8,NaN,NaN,26.8000,6.20612,20.5939,...,NaN,1.64,10.9032,16.3415,NaN,NaN,NaN,NaN,NaN,NaN
22,AZD.F,-0.105956,2.163178,en-US,40.805 - 40.805,NaN,NaN,40.8050,-4.83594,45.6409,...,0.00389911,-3.102,1.68226,NaN,"Aaron's, Inc.",2021-02-20,NaN,NaN,NaN,NaN
23,QGJ.F,0.322894,1.960123,en-US,96.5 - 96.5,NaN,NaN,96.5000,23.5538,72.9462,...,0.0238579,8.22,4.0358,11.7397,NaN,NaN,NaN,NaN,NaN,NaN
24,KKKUF,0.275855,1.251136,en-US,34.69 - 34.69,NaN,NaN,34.6900,7.5004,27.1896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
datas

,symbol,twoHundredDayAverageChangePercent,fiftyTwoWeekLowChangePercent,language,regularMarketDayRange,earningsTimestampEnd,epsForward,regularMarketDayHigh,twoHundredDayAverageChange,twoHundredDayAverage,...,trailingAnnualDividendYield,epsTrailingTwelveMonths,priceToBook,trailingPE,prevName,nameChangeDate,dividendDate,ipoExpectedDate,newListingDate,underlyingSymbol
0,SNDL,1.96503,10.086956,en-US,1.22 - 1.71,1605177000,-0.44,1.7100,1.01399,0.516015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RMM.L,-0.382971,0.691542,en-US,0.305 - 0.3485,1620993600,NaN,0.3485,-0.211028,0.551028,...,0.0222222,-1.1,11.3333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VAST.L,-0.272839,0.183673,en-US,0.1113 - 0.1198,1611745140,NaN,0.1198,-0.0435245,0.159524,...,NaN,-0.1,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002002.SZ,-0.0344986,0.285714,en-US,3.34 - 3.57,1619780340,0.56,3.5700,-0.125417,3.63542,...,0.0178042,0.282,1.17,12.4468,NaN,NaN,NaN,NaN,NaN,NaN
4,UJO.L,-0.125917,1.133333,en-US,0.155 - 0.1687,1620993600,NaN,0.1687,-0.023049,0.183049,...,NaN,-0,160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,AGJ.F,0.253336,1.849091,en-US,94.02 - 94.02,NaN,NaN,94.0200,19.0042,75.0158,...,0.00656814,5.65,2.36314,16.6407,NaN,NaN,NaN,NaN,NaN,NaN
21,TPD.F,0.301357,3.872727,en-US,26.8 - 26.8,NaN,NaN,26.8000,6.20612,20.5939,...,NaN,1.64,10.9032,16.3415,NaN,NaN,NaN,NaN,NaN,NaN
22,AZD.F,-0.105956,2.163178,en-US,40.805 - 40.805,NaN,NaN,40.8050,-4.83594,45.6409,...,0.00389911,-3.102,1.68226,NaN,"Aaron's, Inc.",2021-02-20,NaN,NaN,NaN,NaN
23,QGJ.F,0.322894,1.960123,en-US,96.5 - 96.5,NaN,NaN,96.5000,23.5538,72.9462,...,0.0238579,8.22,4.0358,11.7397,NaN,NaN,NaN,NaN,NaN,NaN
24,KKKUF,0.275855,1.251136,en-US,34.69 - 34.69,NaN,NaN,34.6900,7.5004,27.1896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8375 entries, 0 to 24
Data columns (total 78 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   symbol                             8375 non-null   object
 1   twoHundredDayAverageChangePercent  8144 non-null   object
 2   fiftyTwoWeekLowChangePercent       8375 non-null   float64
 3   language                           8375 non-null   object
 4   regularMarketDayRange              8375 non-null   object
 5   earningsTimestampEnd               4716 non-null   object
 6   epsForward                         2481 non-null   object
 7   regularMarketDayHigh               8375 non-null   float64
 8   twoHundredDayAverageChange         8144 non-null   object
 9   twoHundredDayAverage               8144 non-null   object
 10  askSize                            7035 non-null   object
 11  marketCap                          8361 non-null   object
 12  fiftyTwoWeekHighChange             8375 non-null   float64
 13  fiftyTwoWeekRange                  8375 non-null   object
 14  fiftyDayAverageChange              8143 non-null   object
 15  averageDailyVolume3Month           8143 non-null   object
 16  exchangeDataDelayedBy              8375 non-null   int64
 17  firstTradeDateMilliseconds         8094 non-null   float64
 18  fiftyTwoWeekLow                    8375 non-null   float64
 19  regularMarketVolume                8375 non-null   int64
 20  market                             8375 non-null   object
 21  postMarketPrice                    1264 non-null   object
 22  quoteSourceName                    7102 non-null   object
 23  messageBoardId                     8375 non-null   object
 24  priceHint                          8375 non-null   int64
 25  exchange                           8375 non-null   object
 26  sourceInterval                     8375 non-null   int64
 27  regularMarketDayLow                8375 non-null   float64
 28  shortName                          8370 non-null   object
 29  region                             8375 non-null   object
 30  fiftyDayAverageChangePercent       8143 non-null   object
 31  fullExchangeName                   8375 non-null   object
 32  earningsTimestampStart             4716 non-null   object
 33  financialCurrency                  8334 non-null   object
 34  displayName                        1561 non-null   object
 35  gmtOffSetMilliseconds              8375 non-null   int64
 36  regularMarketOpen                  8374 non-null   object
 37  regularMarketTime                  8375 non-null   int64
 38  regularMarketChangePercent         8375 non-null   float64
 39  quoteType                          8375 non-null   object
 40  averageDailyVolume10Day            8143 non-null   object
 41  fiftyTwoWeekLowChange              8375 non-null   float64
 42  fiftyTwoWeekHighChangePercent      8375 non-null   float64
 43  tradeable                          8375 non-null   bool
 44  postMarketTime                     1264 non-null   object
 45  currency                           8374 non-null   object
 46  sharesOutstanding                  8361 non-null   object
 47  fiftyTwoWeekHigh                   8375 non-null   float64
 48  regularMarketPreviousClose         8375 non-null   float64
 49  exchangeTimezoneName               8375 non-null   object
 50  postMarketChangePercent            1264 non-null   object
 51  bidSize                            7035 non-null   object
 52  regularMarketChange                8375 non-null   float64
 53  priceEpsCurrentYear                1241 non-null   object
 54  fiftyDayAverage                    8143 non-null   object
 55  exchangeTimezoneShortName          8375 non-null   object
 56  epsCurrentYear                     1243 non-null   object
 57  marketState                        8375 non-null   object
 58  regularMarketPrice                 8375 non-null   float64
 59  forwardPE                          2474 non-null   object
 60  postMarketChange                   1264 non-null   object
 61  earningsTimestamp                  4737 non-null   object
 62  ask                                8172 non-null   object
 63  bid                                8172 non-null   object
 64  triggerable                        8375 non-null   bool
 65  longName                           8375 non-null   object
 66  bookValue                          7757 non-null   object
 67  trailingAnnualDividendRate         5432 non-null   object
 68  trailingAnnualDividendYield        5432 non-null   object
 69  epsTrailingTwelveMonths            7752 non-null   object
 70  priceToBook                        7753 non-null   object
 71  trailingPE                         5512 non-null   object
 72  prevName                           143 non-null    object
 73  nameChangeDate                     143 non-null    object
 74  dividendDate                       1352 non-null   object
 75  ipoExpectedDate                    73 non-null     object
 76  newListingDate                     1 non-null      object
 77  underlyingSymbol                   11 non-null     object
dtypes: bool(2), float64(13), int64(6), object(57)
memory usage: 4.9+ MB

In [110]:
newdata=datas[['symbol','trailingPE','marketCap','fiftyTwoWeekLowChangePercent','fiftyTwoWeekHighChangePercent','fiftyTwoWeekRange','trailingPE','displayName','market']]

In [111]:
newdata.sample(25)

,symbol,trailingPE,marketCap,fiftyTwoWeekLowChangePercent,fiftyTwoWeekHighChangePercent,fiftyTwoWeekRange,trailingPE,displayName,market
16,002228.SZ,15.8943,4843004416,0.195719,-0.371383,3.27 - 6.22,15.8943,NaN,cn_market
1,QFI.F,10.6707,7524142592,1.093301,-0.125000,41.8 - 100.0,10.6707,NaN,dr_market
23,7601.T,NaN,4007682048,0.072555,-0.296066,317.0 - 483.0,NaN,NaN,jp_market
1,BRRDF,NaN,1981570432,1.290909,0.000000,8.25 - 18.9,NaN,Borregaard,us_market
2,FDK.F,28.4309,2384688384,0.098825,-0.285393,57.88 - 89.0,28.4309,NaN,dr_market
22,4750.T,62.6745,3886211328,0.087971,-0.119186,557.0 - 688.0,62.6745,NaN,jp_market
8,PRLD,NaN,3584673536,2.248217,-0.193080,23.693 - 95.375,NaN,NaN,us_market
0,KWI.F,24.4364,3854222336,0.953488,-0.096774,17.2 - 37.2,24.4364,NaN,dr_market
0,EQC-PD,8.58625,4542646784,0.270124,-0.042839,24.1 - 31.98,8.58625,NaN,us_market
16,1446.T,30.1845,5789987840,0.677019,-0.330025,322.0 - 806.0,30.1845,NaN,jp_market
14,RGEDF,NaN,5350462464,0.630549,0.000000,18.1058 - 29.5224,NaN,NaN,us_market
13,NWSGY,NaN,4492917248,0.488498,-0.147947,7.39 - 12.91,NaN,NWS,us_market
5,DCPH,NaN,2562047488,0.343202,-0.350000,33.1 - 68.4,NaN,Deciphera Pharmaceuticals,us_market
20,CS0.F,20.339,9456912384,0.875000,-0.215686,0.64 - 1.53,20.339,NaN,dr_market
8,0J2O.L,318.325,7940289536,0.000000,0.000000,49.022 - 49.022,318.325,NaN,gb_market
13,2300.T,12.5857,2830541824,0.537143,-0.115132,350.0 - 608.0,12.5857,NaN,jp_market
23,603058.SS,19.1282,3126291968,0.201288,-0.424383,6.21 - 12.96,19.1282,NaN,cn_market
0,300484.SZ,NaN,2475200000,0.561680,-0.556797,7.62 - 26.85,NaN,NaN,cn_market
22,2286.T,4.2423,5519717376,0.383929,-0.100145,448.0 - 689.0,4.2423,NaN,jp_market
15,RAZFF,NaN,3568956928,0.464643,-0.136632,0.28 - 0.475,NaN,Razer,us_market
10,9SH.F,NaN,4285932800,2.552632,-0.055504,28.5 - 107.2,NaN,NaN,dr_market
24,YHA.F,15.4889,7651593728,0.437086,-0.149020,30.2 - 51.0,15.4889,NaN,dr_market
16,MKT.F,21.485,7768061440,1.060606,-0.133758,66.0 - 157.0,21.485,NaN,dr_market
3,7057.T,17.0964,4058650624,1.204189,-0.080786,573.0 - 1374.0,17.0964,NaN,jp_market
19,CX,NaN,9562793984,3.083871,-0.070485,1.55 - 6.81,NaN,Cemex,us_market

In [132]:
newdata.loc[newdata['market'] == 'us_market'].sample(100)

,symbol,PE Ratio,marketCap,fiftyTwoWeekLowChangePercent,fiftyTwoWeekHighChangePercent,fiftyTwoWeekRange,PE Ratio,displayName,market
6,GO,5185,3905383424,0.475631,-0.151218,28.11 - 48.87,5185,Grocery Outlet,us_market
4,DRTGF,9.39345,3632177408,7.750000,-0.190751,2.0 - 21.625,9.39345,Dart,us_market
3,PTKFF,NaN,5094089728,8.000000,-0.250000,0.0125 - 0.15,NaN,Kalbe Farma,us_market
18,NLLSF,NaN,4666432000,0.065831,-0.190476,3.19 - 4.2,NaN,NEL,us_market
19,TV,14.4685,4528928256,0.726882,-0.287489,4.65 - 11.27,14.4685,NaN,us_market
...,...,...,...,...,...,...,...,...,...
20,CACI,16.0041,5931878912,0.505604,-0.131094,156.15 - 270.57,16.0041,CACI,us_market
4,NSA,79.2437,2610133504,0.950362,-0.029336,19.34 - 38.86,79.2437,National Storage,us_market
10,BMI,62.7219,3086402048,1.554217,-0.029215,41.5 - 109.19,62.7219,Badger Meter,us_market
5,DCPH,NaN,2562047488,0.343202,-0.350000,33.1 - 68.4,NaN,Deciphera Pharmaceuticals,us_market
9,ROLL,48.2437,4778535424,1.448538,-0.002048,77.63 - 190.47,48.2437,RBC Bearings,us_market

In [131]:
newdata = newdata.rename(columns={'trailingPE': 'PE Ratio'})

In [116]:
newdata.to_csv (r'/Users/teahupoo20/Documents/GitHub/data-ft-par-labs/Projects/Week-3/newdata.csv')

In [117]:
import pymysql
from sqlalchemy import create_engine
from getpass import getpass

In [128]:
username='root'
server='localhost'
database='ironhack'
password=getpass()

engine=create_engine(f'mysql+pymysql://{username}:{password}@{server}/ironhack')

········

In [129]:
newdata.to_sql('yahoo_finance', con=engine,index=False,if_exists='append')

OperationalError: (pymysql.err.OperationalError) (1046, 'No database selected')
[SQL: DESCRIBE `yahoo_finance`]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [ ]:
datas.display.max_columns

In [ ]:
datas

In [ ]:
resp.json()['finance']['result'][0]['quotes']

In [ ]:
datas.shape

In [ ]:
a = {"a":1,"b":2,"c":3,"f":4,"d":5}
b= ["b","c"]

out = {item:a.get(item)for item in b}

In [ ]:
out