In [18]:
"""
read a Sharks DB,
drop weird columns,
rename columns,
drop rows with all missing,
sort by some column
reindex
"""


import os
import pandas as pd
df= pd.read_csv('attacks.csv',encoding='ISO-8859-1')


df.drop(columns=['href formula', 'href', 'Unnamed: 22', 'Unnamed: 23', "Case Number.1", "Case Number.2", 'pdf', 'original order'], axis=1, inplace = True)

df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF"
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com"
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com"
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF"
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.dropna(inplace = True)
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF"
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018"
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com"
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018"
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5814,1880.11.25,25-Nov-1880,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,"Feet bitten, surgically amputated FATAL",Y,Afternoon,Bull shark,"Bucks County Gazette, 2/10/1881, Sunday Mail (..."
5922,1868.05.13,13-May-1868,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,"FATAL, upper left thigh, groin & buttocks seve...",Y,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,"J. Fayrer, M.D."
6242,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,6,Arm severed,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan
6243,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,16,Right leg lacerated & surgically amputated,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan
6265,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,13 or 14,"FATAL, left leg bitten with severe blood loss",Y,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan

In [20]:
df.sort_values(by='Area', ascending=False, inplace = True)
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source
607,2013.10.26.b,26-Oct-2013,2013.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Body boarding,Gicquel Tanguy,M,24,Right leg severed,N,16h30,Thought to involve a bull shark,"Global Post, 10/26/2013"
447,2015.02.14,14-Feb-2015,2015.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Swimming,Talon Bishop,F,22,FATAL,Y,18h30,"Tiger shark, 3.5 m","L'Yonne Républicaine, 2/14/2015"
3739,1963.09.22,22-Sep-1963,1963.0,Unprovoked,SOLOMON ISLANDS,Ysabel Island,Susukana Plantation,Spearing fish,Dovi,M,30,"FATAL, right thigh, calf & foot bitten",Y,13h00,5.5 m [18'] shark,"M.L. Aylett, Fisheries Officer; H.D. Baldridge..."
5224,1922.05.24,24-May 1922,1922.0,Unprovoked,JAMAICA,Westmoreland Parish,Savanna-la-Mar,Swimming,Sausse Leon,M,19,"FATAL, arm severed, thigh severely bitten",Y,10h00,6' shark,"Daily Gleaner, 5/25/1922; H.E. Lloyd, NY Times..."
1051,2010.01.12,12-Jan-2010,2010.0,Unprovoked,SOUTH AFRICA,Western Province,Fish Hoek,Standing,Lloyd Skinner,M,37,FATAL,Y,15h15,White shark,"L. Cohen, Times Live, 1/12/2010"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3850,1962.01.11.b,11-Jan-1962,1962.0,Unprovoked,PAPUA NEW GUINEA,"10ºS, 142ºE",Jukuataia Village,Spearfishing,Yagirua Agiramon,M,24,Left leg & buttocks bitten,N,12h00,White shark,SAF Case #1193
1199,2008.10.06,06-Oct-2008,2008.0,Unprovoked,CROATIA,"Split-Dalmatia Count,","Smokvina Bay, Vis Island",Spearfishing,Damjan Pecek,M,43,Calf bitten,N,12h00,5 m white shark,A. De Maddalena
943,2011.02.23,23-Feb-2011,2011.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,"Bay of Bweedro, Ouvéa",Spearfishing,Jean-Luc Majele,M,21,Lacerations to left forearm,N,Early afternoon,1.5 m shark,"Les Nouvelles Caledoniennes, 2/25/2011"
3728,1963.11.28,28-Nov-1963,1963.0,Unprovoked,FIJI,Lau Province,"Dravuwalu, Totoya Island",Fishing,"Mereseini Wati, female",F,21,Elbow bitten,N,11h00,>1.2 m [4'] tiger shark,Capt. S. B. Brown
4463,1950.08.06,06-Aug-1950,1950.0,Provoked,EL SALVADOR,La Libertad,50 miles off Port La Libertad,Jerked overboard while pole fishing for tuna,Robert L. Bottini,M,27,Left thigh bitten by hooked shark PROVOKED INC...,N,08h30,"1,100-lb shark","Evening Sun (Baltimore), 8/11/1950; Long Beach..."

In [24]:
ix=pd.Index(list('Date'), name='Reindex Date')

ix.name

'Reindex Date'

In [85]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source
607,2013.10.26.b,26-Oct-2013,2013.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Body boarding,Gicquel Tanguy,M,24,Right leg severed,N,16h30,Thought to involve a bull shark,"Global Post, 10/26/2013"
447,2015.02.14,14-Feb-2015,2015.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Swimming,Talon Bishop,F,22,FATAL,Y,18h30,"Tiger shark, 3.5 m","L'Yonne Républicaine, 2/14/2015"
3739,1963.09.22,22-Sep-1963,1963.0,Unprovoked,SOLOMON ISLANDS,Ysabel Island,Susukana Plantation,Spearing fish,Dovi,M,30,"FATAL, right thigh, calf & foot bitten",Y,13h00,5.5 m [18'] shark,"M.L. Aylett, Fisheries Officer; H.D. Baldridge..."
5224,1922.05.24,24-May 1922,1922.0,Unprovoked,JAMAICA,Westmoreland Parish,Savanna-la-Mar,Swimming,Sausse Leon,M,19,"FATAL, arm severed, thigh severely bitten",Y,10h00,6' shark,"Daily Gleaner, 5/25/1922; H.E. Lloyd, NY Times..."
1051,2010.01.12,12-Jan-2010,2010.0,Unprovoked,SOUTH AFRICA,Western Province,Fish Hoek,Standing,Lloyd Skinner,M,37,FATAL,Y,15h15,White shark,"L. Cohen, Times Live, 1/12/2010"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3850,1962.01.11.b,11-Jan-1962,1962.0,Unprovoked,PAPUA NEW GUINEA,"10ºS, 142ºE",Jukuataia Village,Spearfishing,Yagirua Agiramon,M,24,Left leg & buttocks bitten,N,12h00,White shark,SAF Case #1193
1199,2008.10.06,06-Oct-2008,2008.0,Unprovoked,CROATIA,"Split-Dalmatia Count,","Smokvina Bay, Vis Island",Spearfishing,Damjan Pecek,M,43,Calf bitten,N,12h00,5 m white shark,A. De Maddalena
943,2011.02.23,23-Feb-2011,2011.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,"Bay of Bweedro, Ouvéa",Spearfishing,Jean-Luc Majele,M,21,Lacerations to left forearm,N,Early afternoon,1.5 m shark,"Les Nouvelles Caledoniennes, 2/25/2011"
3728,1963.11.28,28-Nov-1963,1963.0,Unprovoked,FIJI,Lau Province,"Dravuwalu, Totoya Island",Fishing,"Mereseini Wati, female",F,21,Elbow bitten,N,11h00,>1.2 m [4'] tiger shark,Capt. S. B. Brown
4463,1950.08.06,06-Aug-1950,1950.0,Provoked,EL SALVADOR,La Libertad,50 miles off Port La Libertad,Jerked overboard while pole fishing for tuna,Robert L. Bottini,M,27,Left thigh bitten by hooked shark PROVOKED INC...,N,08h30,"1,100-lb shark","Evening Sun (Baltimore), 8/11/1950; Long Beach..."

In [93]:
df.reset_index()

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source
0,607,2013.10.26.b,26-Oct-2013,2013.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Body boarding,Gicquel Tanguy,M,24,Right leg severed,N,16h30,Thought to involve a bull shark,"Global Post, 10/26/2013"
1,447,2015.02.14,14-Feb-2015,2015.0,Unprovoked,REUNION,dÉtang-Salé,Ravine Mula,Swimming,Talon Bishop,F,22,FATAL,Y,18h30,"Tiger shark, 3.5 m","L'Yonne Républicaine, 2/14/2015"
2,3739,1963.09.22,22-Sep-1963,1963.0,Unprovoked,SOLOMON ISLANDS,Ysabel Island,Susukana Plantation,Spearing fish,Dovi,M,30,"FATAL, right thigh, calf & foot bitten",Y,13h00,5.5 m [18'] shark,"M.L. Aylett, Fisheries Officer; H.D. Baldridge..."
3,5224,1922.05.24,24-May 1922,1922.0,Unprovoked,JAMAICA,Westmoreland Parish,Savanna-la-Mar,Swimming,Sausse Leon,M,19,"FATAL, arm severed, thigh severely bitten",Y,10h00,6' shark,"Daily Gleaner, 5/25/1922; H.E. Lloyd, NY Times..."
4,1051,2010.01.12,12-Jan-2010,2010.0,Unprovoked,SOUTH AFRICA,Western Province,Fish Hoek,Standing,Lloyd Skinner,M,37,FATAL,Y,15h15,White shark,"L. Cohen, Times Live, 1/12/2010"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,3850,1962.01.11.b,11-Jan-1962,1962.0,Unprovoked,PAPUA NEW GUINEA,"10ºS, 142ºE",Jukuataia Village,Spearfishing,Yagirua Agiramon,M,24,Left leg & buttocks bitten,N,12h00,White shark,SAF Case #1193
1418,1199,2008.10.06,06-Oct-2008,2008.0,Unprovoked,CROATIA,"Split-Dalmatia Count,","Smokvina Bay, Vis Island",Spearfishing,Damjan Pecek,M,43,Calf bitten,N,12h00,5 m white shark,A. De Maddalena
1419,943,2011.02.23,23-Feb-2011,2011.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,"Bay of Bweedro, Ouvéa",Spearfishing,Jean-Luc Majele,M,21,Lacerations to left forearm,N,Early afternoon,1.5 m shark,"Les Nouvelles Caledoniennes, 2/25/2011"
1420,3728,1963.11.28,28-Nov-1963,1963.0,Unprovoked,FIJI,Lau Province,"Dravuwalu, Totoya Island",Fishing,"Mereseini Wati, female",F,21,Elbow bitten,N,11h00,>1.2 m [4'] tiger shark,Capt. S. B. Brown
1421,4463,1950.08.06,06-Aug-1950,1950.0,Provoked,EL SALVADOR,La Libertad,50 miles off Port La Libertad,Jerked overboard while pole fishing for tuna,Robert L. Bottini,M,27,Left thigh bitten by hooked shark PROVOKED INC...,N,08h30,"1,100-lb shark","Evening Sun (Baltimore), 8/11/1950; Long Beach..."

In [94]:
df.to_csv('new_attacks.csv', encoding='utf-8')