# PROJECT WEEK 3 DATA ANALYST IRONHACK Edwin Pitono

## Web Scraping Yahoo Finance
The idea here is to scrap financial data from Yahoo Finance website (I chose page the most active stocks) and try to answer a question

In [3]:
# first things first. I found out that the website uses API POST. So no need for beautiful soup.
import requests as r
import time
import pandas as pd

In [4]:
link='https://query1.finance.yahoo.com/v1/finance/screener?crumb=00%2Finl.UKdq&lang=en-US&region=US&formatted=true&corsDomain=finance.yahoo.com'

In [5]:
# The pagination is located at the payload. I put time sleep 3 seconds as well because the data wasn't full (9100 ish) when I didn't use it (I got around 7000)

datas=pd.DataFrame()
for i in range(0,9125,25):
    headers="""accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7
cache-control: no-cache
content-length: 566
content-type: application/json
cookie: APID=UPd136432b-66b5-11eb-8c62-0291f2e222b6; B=1rmiql5g0u7kh&b=3&s=qm; A1=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A3=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc; A1S=d=AQABBJEeD2ACEM3sxN7U_y0JfchRPqla2h0FEgABAgE9LWD1YPbPb2UBgiIAAAcIkR4PYKla2h0&S=AQAAAjENqnJP2GCwA9rr5y9Zcyc&j=GDPR; GUC=AQABAgFgLT1g9UIgiASi; EuConsent=CPBtzigPBtzigAOACCENBACgAAAAAAAAACiQAAAAAAAA; thamba=2; cmp=v=18&t=1613658098&j=1
origin: https://finance.yahoo.com
pragma: no-cache
referer: https://finance.yahoo.com/most-active?count=25&offset=25
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"""
    payload="""{"offset":"""+str(i)+""","size":25,"sortField":"dayvolume","sortType":"DESC","quoteType":"EQUITY","query":{"operator":"AND","operands":[{"operator":"or","operands":[{"operator":"EQ","operands":["region","us"]},{"operator":"EQ","operands":["region","fr"]},{"operator":"EQ","operands":["region","gb"]},{"operator":"EQ","operands":["region","de"]},{"operator":"EQ","operands":["region","cn"]},{"operator":"EQ","operands":["region","jp"]}]},{"operator":"or","operands":[{"operator":"BTWN","operands":["intradaymarketcap",2000000000,10000000000]}]}]},"userId":"","userIdType":"guid"}"""
    headers= dict(i.split(': ') for i in headers.split('\n'))
    resp=r.post(link, headers=headers, data=payload)
    data=resp.json()['finance']['result'][0]['quotes']
    pd.DataFrame(data)
    print(i," datas are scrapped")
    datas=datas.append(data)
    print("data appended")
    time.sleep(3)
print("Done!")

0  datas are scrapped
data appended
25  datas are scrapped
data appended
50  datas are scrapped
data appended
75  datas are scrapped
data appended
100  datas are scrapped
data appended
125  datas are scrapped
data appended
150  datas are scrapped
data appended
175  datas are scrapped
data appended
200  datas are scrapped
data appended
225  datas are scrapped
data appended
250  datas are scrapped
data appended
275  datas are scrapped
data appended
300  datas are scrapped
data appended
325  datas are scrapped
data appended
350  datas are scrapped
data appended
375  datas are scrapped
data appended
400  datas are scrapped
data appended
425  datas are scrapped
data appended
450  datas are scrapped
data appended
475  datas are scrapped
data appended
500  datas are scrapped
data appended
525  datas are scrapped
data appended
550  datas are scrapped
data appended
575  datas are scrapped
data appended
600  datas are scrapped
data appended
625  datas are scrapped
data appended
650  datas are scrapped
data appended
675  datas are scrapped
data appended
700  datas are scrapped
data appended
725  datas are scrapped
data appended
750  datas are scrapped
data appended
775  datas are scrapped
data appended
800  datas are scrapped
data appended
825  datas are scrapped
data appended
850  datas are scrapped
data appended
875  datas are scrapped
data appended
900  datas are scrapped
data appended
925  datas are scrapped
data appended
950  datas are scrapped
data appended
975  datas are scrapped
data appended
1000  datas are scrapped
data appended
1025  datas are scrapped
data appended
1050  datas are scrapped
data appended
1075  datas are scrapped
data appended
1100  datas are scrapped
data appended
1125  datas are scrapped
data appended
1150  datas are scrapped
data appended
1175  datas are scrapped
data appended
1200  datas are scrapped
data appended
1225  datas are scrapped
data appended
1250  datas are scrapped
data appended
1275  datas are scrapped
data appended
1300  datas are scrapped
data appended
1325  datas are scrapped
data appended
1350  datas are scrapped
data appended
1375  datas are scrapped
data appended
1400  datas are scrapped
data appended
1425  datas are scrapped
data appended
1450  datas are scrapped
data appended
1475  datas are scrapped
data appended
1500  datas are scrapped
data appended
1525  datas are scrapped
data appended
1550  datas are scrapped
data appended
1575  datas are scrapped
data appended
1600  datas are scrapped
data appended
1625  datas are scrapped
data appended
1650  datas are scrapped
data appended
1675  datas are scrapped
data appended
1700  datas are scrapped
data appended
1725  datas are scrapped
data appended
1750  datas are scrapped
data appended
1775  datas are scrapped
data appended
1800  datas are scrapped
data appended
1825  datas are scrapped
data appended
1850  datas are scrapped
data appended
1875  datas are scrapped
data appended
1900  datas are scrapped
data appended
1925  datas are scrapped
data appended
1950  datas are scrapped
data appended
1975  datas are scrapped
data appended
2000  datas are scrapped
data appended
2025  datas are scrapped
data appended
2050  datas are scrapped
data appended
2075  datas are scrapped
data appended
2100  datas are scrapped
data appended
2125  datas are scrapped
data appended
2150  datas are scrapped
data appended
2175  datas are scrapped
data appended
2200  datas are scrapped
data appended
2225  datas are scrapped
data appended
2250  datas are scrapped
data appended
2275  datas are scrapped
data appended
2300  datas are scrapped
data appended
2325  datas are scrapped
data appended
2350  datas are scrapped
data appended
2375  datas are scrapped
data appended
2400  datas are scrapped
data appended
2425  datas are scrapped
data appended
2450  datas are scrapped
data appended
2475  datas are scrapped
data appended
2500  datas are scrapped
data appended
2525  datas are scrapped
data appended
2550  datas are scrapped
data appended
2575  datas are scrapped
data appended
2600  datas are scrapped
data appended
2625  datas are scrapped
data appended
2650  datas are scrapped
data appended
2675  datas are scrapped
data appended
2700  datas are scrapped
data appended
2725  datas are scrapped
data appended
2750  datas are scrapped
data appended
2775  datas are scrapped
data appended
2800  datas are scrapped
data appended
2825  datas are scrapped
data appended
2850  datas are scrapped
data appended
2875  datas are scrapped
data appended
2900  datas are scrapped
data appended
2925  datas are scrapped
data appended
2950  datas are scrapped
data appended
2975  datas are scrapped
data appended
3000  datas are scrapped
data appended
3025  datas are scrapped
data appended
3050  datas are scrapped
data appended
3075  datas are scrapped
data appended
3100  datas are scrapped
data appended
3125  datas are scrapped
data appended
3150  datas are scrapped
data appended
3175  datas are scrapped
data appended
3200  datas are scrapped
data appended
3225  datas are scrapped
data appended
3250  datas are scrapped
data appended
3275  datas are scrapped
data appended
3300  datas are scrapped
data appended
3325  datas are scrapped
data appended
3350  datas are scrapped
data appended
3375  datas are scrapped
data appended
3400  datas are scrapped
data appended
3425  datas are scrapped
data appended
3450  datas are scrapped
data appended
3475  datas are scrapped
data appended
3500  datas are scrapped
data appended
3525  datas are scrapped
data appended
3550  datas are scrapped
data appended
3575  datas are scrapped
data appended
3600  datas are scrapped
data appended
3625  datas are scrapped
data appended
3650  datas are scrapped
data appended
3675  datas are scrapped
data appended
3700  datas are scrapped
data appended
3725  datas are scrapped
data appended
3750  datas are scrapped
data appended
3775  datas are scrapped
data appended
3800  datas are scrapped
data appended
3825  datas are scrapped
data appended
3850  datas are scrapped
data appended
3875  datas are scrapped
data appended
3900  datas are scrapped
data appended
3925  datas are scrapped
data appended
3950  datas are scrapped
data appended
3975  datas are scrapped
data appended
4000  datas are scrapped
data appended
4025  datas are scrapped
data appended
4050  datas are scrapped
data appended
4075  datas are scrapped
data appended
4100  datas are scrapped
data appended
4125  datas are scrapped
data appended
4150  datas are scrapped
data appended
4175  datas are scrapped
data appended
4200  datas are scrapped
data appended
4225  datas are scrapped
data appended
4250  datas are scrapped
data appended
4275  datas are scrapped
data appended
4300  datas are scrapped
data appended
4325  datas are scrapped
data appended
4350  datas are scrapped
data appended
4375  datas are scrapped
data appended
4400  datas are scrapped
data appended
4425  datas are scrapped
data appended
4450  datas are scrapped
data appended
4475  datas are scrapped
data appended
4500  datas are scrapped
data appended
4525  datas are scrapped
data appended
4550  datas are scrapped
data appended
4575  datas are scrapped
data appended
4600  datas are scrapped
data appended
4625  datas are scrapped
data appended
4650  datas are scrapped
data appended
4675  datas are scrapped
data appended
4700  datas are scrapped
data appended
4725  datas are scrapped
data appended
4750  datas are scrapped
data appended
4775  datas are scrapped
data appended
4800  datas are scrapped
data appended
4825  datas are scrapped
data appended
4850  datas are scrapped
data appended
4875  datas are scrapped
data appended
4900  datas are scrapped
data appended
4925  datas are scrapped
data appended
4950  datas are scrapped
data appended
4975  datas are scrapped
data appended
5000  datas are scrapped
data appended
5025  datas are scrapped
data appended
5050  datas are scrapped
data appended
5075  datas are scrapped
data appended
5100  datas are scrapped
data appended
5125  datas are scrapped
data appended
5150  datas are scrapped
data appended
5175  datas are scrapped
data appended
5200  datas are scrapped
data appended
5225  datas are scrapped
data appended
5250  datas are scrapped
data appended
5275  datas are scrapped
data appended

5300  datas are scrapped
data appended
5325  datas are scrapped
data appended
5350  datas are scrapped
data appended
5375  datas are scrapped
data appended
5400  datas are scrapped
data appended
5425  datas are scrapped
data appended
5450  datas are scrapped
data appended
5475  datas are scrapped
data appended
5500  datas are scrapped
data appended
5525  datas are scrapped
data appended
5550  datas are scrapped
data appended
5575  datas are scrapped
data appended
5600  datas are scrapped
data appended
5625  datas are scrapped
data appended
5650  datas are scrapped
data appended
5675  datas are scrapped
data appended
5700  datas are scrapped
data appended
5725  datas are scrapped
data appended
5750  datas are scrapped
data appended
5775  datas are scrapped
data appended
5800  datas are scrapped
data appended
5825  datas are scrapped
data appended
5850  datas are scrapped
data appended
5875  datas are scrapped
data appended
5900  datas are scrapped
data appended
5925  datas are scrapped
data appended
5950  datas are scrapped
data appended
5975  datas are scrapped
data appended
6000  datas are scrapped
data appended
6025  datas are scrapped
data appended
6050  datas are scrapped
data appended
6075  datas are scrapped
data appended
6100  datas are scrapped
data appended
6125  datas are scrapped
data appended
6150  datas are scrapped
data appended
6175  datas are scrapped
data appended
6200  datas are scrapped
data appended
6225  datas are scrapped
data appended
6250  datas are scrapped
data appended
6275  datas are scrapped
data appended
6300  datas are scrapped
data appended
6325  datas are scrapped
data appended
6350  datas are scrapped
data appended
6375  datas are scrapped
data appended
6400  datas are scrapped
data appended
6425  datas are scrapped
data appended
6450  datas are scrapped
data appended
6475  datas are scrapped
data appended
6500  datas are scrapped
data appended
6525  datas are scrapped
data appended
6550  datas are scrapped
data appended
6575  datas are scrapped
data appended
6600  datas are scrapped
data appended
6625  datas are scrapped
data appended
6650  datas are scrapped
data appended
6675  datas are scrapped
data appended
6700  datas are scrapped
data appended
6725  datas are scrapped
data appended
6750  datas are scrapped
data appended
6775  datas are scrapped
data appended
6800  datas are scrapped
data appended
6825  datas are scrapped
data appended
6850  datas are scrapped
data appended
6875  datas are scrapped
data appended
6900  datas are scrapped
data appended
6925  datas are scrapped
data appended
6950  datas are scrapped
data appended
6975  datas are scrapped
data appended
7000  datas are scrapped
data appended
7025  datas are scrapped
data appended
7050  datas are scrapped
data appended
7075  datas are scrapped
data appended
7100  datas are scrapped
data appended
7125  datas are scrapped
data appended
7150  datas are scrapped
data appended
7175  datas are scrapped
data appended
7200  datas are scrapped
data appended
7225  datas are scrapped
data appended
7250  datas are scrapped
data appended
7275  datas are scrapped
data appended
7300  datas are scrapped
data appended
7325  datas are scrapped
data appended
7350  datas are scrapped
data appended
7375  datas are scrapped
data appended
7400  datas are scrapped
data appended
7425  datas are scrapped
data appended
7450  datas are scrapped
data appended
7475  datas are scrapped
data appended
7500  datas are scrapped
data appended
7525  datas are scrapped
data appended
7550  datas are scrapped
data appended
7575  datas are scrapped
data appended
7600  datas are scrapped
data appended
7625  datas are scrapped
data appended
7650  datas are scrapped
data appended
7675  datas are scrapped
data appended
7700  datas are scrapped
data appended
7725  datas are scrapped
data appended
7750  datas are scrapped
data appended
7775  datas are scrapped
data appended
7800  datas are scrapped
data appended
7825  datas are scrapped
data appended
7850  datas are scrapped
data appended
7875  datas are scrapped
data appended
7900  datas are scrapped
data appended
7925  datas are scrapped
data appended
7950  datas are scrapped
data appended
7975  datas are scrapped
data appended
8000  datas are scrapped
data appended
8025  datas are scrapped
data appended
8050  datas are scrapped
data appended
8075  datas are scrapped
data appended
8100  datas are scrapped
data appended
8125  datas are scrapped
data appended
8150  datas are scrapped
data appended
8175  datas are scrapped
data appended
8200  datas are scrapped
data appended
8225  datas are scrapped
data appended
8250  datas are scrapped
data appended
8275  datas are scrapped
data appended
8300  datas are scrapped
data appended
8325  datas are scrapped
data appended
8350  datas are scrapped
data appended
8375  datas are scrapped
data appended
8400  datas are scrapped
data appended
8425  datas are scrapped
data appended
8450  datas are scrapped
data appended
8475  datas are scrapped
data appended
8500  datas are scrapped
data appended
8525  datas are scrapped
data appended
8550  datas are scrapped
data appended
8575  datas are scrapped
data appended
8600  datas are scrapped
data appended
8625  datas are scrapped
data appended
8650  datas are scrapped
data appended
8675  datas are scrapped
data appended
8700  datas are scrapped
data appended
8725  datas are scrapped
data appended
8750  datas are scrapped
data appended
8775  datas are scrapped
data appended
8800  datas are scrapped
data appended
8825  datas are scrapped
data appended
8850  datas are scrapped
data appended
8875  datas are scrapped
data appended
8900  datas are scrapped
data appended
8925  datas are scrapped
data appended
8950  datas are scrapped
data appended
8975  datas are scrapped
data appended
9000  datas are scrapped
data appended
9025  datas are scrapped
data appended
9050  datas are scrapped
data appended
9075  datas are scrapped
data appended
9100  datas are scrapped
data appended
Done!

In [72]:
datas[datas['symbol']=='MRO'].iloc[:,0:20]

,symbol,twoHundredDayAverageChangePercent,fiftyTwoWeekLowChangePercent,language,earningsTimestampEnd,regularMarketDayRange,epsForward,regularMarketDayHigh,twoHundredDayAverageChange,twoHundredDayAverage,askSize,fiftyTwoWeekHighChange,marketCap,fiftyTwoWeekRange,fiftyDayAverageChange,averageDailyVolume3Month,firstTradeDateMilliseconds,exchangeDataDelayedBy,fiftyTwoWeekLow,regularMarketVolume
21,MRO,0.584697,2.129139,en-US,"{'raw': 1614027600, 'fmt': '2021-02-22', 'long...",9.14 - 9.48,"{'raw': -0.32, 'fmt': '-0.32'}","{'raw': 9.48, 'fmt': '9.48'}","{'raw': 3.4867153, 'fmt': '3.49'}","{'raw': 5.9632845, 'fmt': '5.96'}","{'raw': 32, 'fmt': '32', 'longFmt': '32'}","{'raw': -0.35000038, 'fmt': '-0.35'}",7459744768,3.02 - 9.8,"{'raw': 1.2718182, 'fmt': '1.27'}",28389240,138600000.0,0,"{'raw': 3.02, 'fmt': '3.02'}","{'raw': 21489513, 'fmt': '21.49M', 'longFmt': ..."

In [101]:
datas[datas['symbol']=='DAL']

Empty DataFrame
Columns: [symbol, twoHundredDayAverageChangePercent, fiftyTwoWeekLowChangePercent, language, earningsTimestampEnd, regularMarketDayRange, epsForward, regularMarketDayHigh, twoHundredDayAverageChange, twoHundredDayAverage, askSize, fiftyTwoWeekHighChange, marketCap, fiftyTwoWeekRange, fiftyDayAverageChange, averageDailyVolume3Month, firstTradeDateMilliseconds, exchangeDataDelayedBy, fiftyTwoWeekLow, regularMarketVolume, market, postMarketPrice, quoteSourceName, messageBoardId, priceHint, exchange, sourceInterval, regularMarketDayLow, region, shortName, fiftyDayAverageChangePercent, fullExchangeName, earningsTimestampStart, financialCurrency, displayName, gmtOffSetMilliseconds, regularMarketOpen, regularMarketTime, regularMarketChangePercent, quoteType, fiftyTwoWeekLowChange, averageDailyVolume10Day, fiftyTwoWeekHighChangePercent, tradeable, postMarketTime, currency, sharesOutstanding, regularMarketPreviousClose, fiftyTwoWeekHigh, exchangeTimezoneName, postMarketChangePercent, bidSize, regularMarketChange, priceEpsCurrentYear, fiftyDayAverage, epsCurrentYear, exchangeTimezoneShortName, regularMarketPrice, marketState, postMarketChange, forwardPE, earningsTimestamp, ask, bid, triggerable, longName, bookValue, trailingAnnualDividendRate, trailingAnnualDividendYield, epsTrailingTwelveMonths, priceToBook, trailingPE, prevName, nameChangeDate, dividendDate, ipoExpectedDate, newListingDate, underlyingSymbol]
Index: []

[0 rows x 78 columns]

In [90]:
datas

,symbol,twoHundredDayAverageChangePercent,fiftyTwoWeekLowChangePercent,language,earningsTimestampEnd,regularMarketDayRange,epsForward,regularMarketDayHigh,twoHundredDayAverageChange,twoHundredDayAverage,...,trailingAnnualDividendYield,epsTrailingTwelveMonths,priceToBook,trailingPE,prevName,nameChangeDate,dividendDate,ipoExpectedDate,newListingDate,underlyingSymbol
0,SNDL,1.92649,10.086956,en-US,"{'raw': 1605177000, 'fmt': '2020-11-12', 'long...",1.22 - 1.71,"{'raw': -0.44, 'fmt': '-0.44'}","{'raw': 1.71, 'fmt': '1.7100'}","{'raw': 1.0071898, 'fmt': '1.01'}","{'raw': 0.5228102, 'fmt': '0.52'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RMM.L,-0.377361,0.691542,en-US,"{'raw': 1620993600, 'fmt': '2021-05-14', 'long...",0.305 - 0.3485,NaN,"{'raw': 0.3485, 'fmt': '0.3485'}","{'raw': -0.20606294, 'fmt': '-0.21'}","{'raw': 0.54606295, 'fmt': '0.55'}",...,0.0222222,"{'raw': -1.1, 'fmt': '-1.1000'}","{'raw': 11.333334, 'fmt': '11.33'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VAST.L,-0.269509,0.183673,en-US,"{'raw': 1611745140, 'fmt': '2021-01-27', 'long...",0.1113 - 0.1198,NaN,"{'raw': 0.1198, 'fmt': '0.1198'}","{'raw': -0.042797208, 'fmt': '-0.04'}","{'raw': 0.1587972, 'fmt': '0.16'}",...,NaN,"{'raw': -0.1, 'fmt': '-0.1000'}","{'raw': 115.99999, 'fmt': '116.00'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002002.SZ,-0.0337838,0.285714,en-US,"{'raw': 1619780340, 'fmt': '2021-04-30', 'long...",3.34 - 3.57,"{'raw': 0.56, 'fmt': '0.56'}","{'raw': 3.57, 'fmt': '3.5700'}","{'raw': -0.122727394, 'fmt': '-0.12'}","{'raw': 3.6327274, 'fmt': '3.63'}",...,0.0178042,"{'raw': 0.282, 'fmt': '0.2820'}","{'raw': 1.17, 'fmt': '1.17'}",12.4468,NaN,NaN,NaN,NaN,NaN,NaN
4,UJO.L,-0.121757,1.133333,en-US,"{'raw': 1620993600, 'fmt': '2021-05-14', 'long...",0.155 - 0.1687,NaN,"{'raw': 0.1687, 'fmt': '0.1687'}","{'raw': -0.022181824, 'fmt': '-0.02'}","{'raw': 0.18218182, 'fmt': '0.18'}",...,NaN,"{'raw': -0.0, 'fmt': '-0.0000'}","{'raw': 159.99998, 'fmt': '160.00'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,CMS.DE,0.651422,0.861152,en-US,NaN,18.9 - 18.9,NaN,"{'raw': 18.9, 'fmt': '18.90'}","{'raw': 7.4553146, 'fmt': '7.46'}","{'raw': 11.444685, 'fmt': '11.44'}",...,0.0253968,"{'raw': 2.157, 'fmt': '2.16'}","{'raw': 1.1729659, 'fmt': '1.17'}",8.76217,NaN,NaN,NaN,NaN,NaN,NaN
22,6RS.SG,-0.141912,0.256881,en-US,NaN,27.4 - 27.4,NaN,"{'raw': 27.4, 'fmt': '27.40'}","{'raw': -4.5314693, 'fmt': '-4.53'}","{'raw': 31.931469, 'fmt': '31.93'}",...,NaN,"{'raw': 1.347, 'fmt': '1.35'}","{'raw': 3.661633, 'fmt': '3.66'}",20.3415,NaN,NaN,NaN,NaN,NaN,NaN
23,TZ6.SG,0.206433,0.866667,en-US,NaN,11.2 - 11.2,NaN,"{'raw': 11.2, 'fmt': '11.20'}","{'raw': 1.9164333, 'fmt': '1.92'}","{'raw': 9.283566, 'fmt': '9.28'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,KSD.F,-0.307559,0.143726,en-US,NaN,11.666 - 11.666,NaN,"{'raw': 11.666, 'fmt': '11.67'}","{'raw': -5.1816463, 'fmt': '-5.18'}","{'raw': 16.847647, 'fmt': '16.85'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,DPR.F,0.248809,0.571429,en-US,NaN,16.5 - 16.5,NaN,"{'raw': 16.5, 'fmt': '16.50'}","{'raw': 3.2874126, 'fmt': '3.29'}","{'raw': 13.212587, 'fmt': '13.21'}",...,0.0059375,"{'raw': 0.232, 'fmt': '0.23'}","{'raw': 1.4529765, 'fmt': '1.45'}",71.1207,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
datas.applymap(lambda x: x.get('raw') if x else x)

AttributeError: 'str' object has no attribute 'get'

In [ ]:
#Since we find that many columns has 'raw' and 'fmt', we want to keep the values of 'raw only'. Here's the line to change this column one by one.
subset = datas['trailingAnnualDividendYield'].copy()
mask = subset.isna()
subset.loc[~mask] = subset.loc[~mask].apply(lambda x: x.get('raw'))
datas['trailingAnnualDividendYield'] = subse

In [55]:
# After cleaning up the columns, I select some columns that would be useful for the research and put them in a new dataframe called newdata
newdata=datas[['symbol','displayName','market','regularMarketPrice','regularMarketDayRange','trailingPE','marketCap','trailingAnnualDividendYield','fiftyTwoWeekLowChangePercent','fiftyTwoWeekHighChangePercent','averageDailyVolume3Month','fiftyTwoWeekRange','priceEpsCurrentYear']]

In [106]:
newdata

,Symbol,Stock Name,Country,Market Price,Day Price Range,PE Ratio,marketCap,Dividend Yield,52 Week Low Price Range Change,52 Week High Price Range Change,3 Month Average Daily Volume,52 Week Price Range,priceEpsCurrentYear
0,SNDL,Sundial Growers,us_market,1.530,1.22 - 1.71,NaN,2388865536,NaN,<built-in method format of str object at 0x7f8...,-0.613636,607019610,0.138 - 3.96,-3.64286
1,RMM.L,NaN,gb_market,0.340,0.305 - 0.3485,NaN,36326280,0.0222222,<built-in method format of str object at 0x7f8...,-0.830000,205115508,0.201 - 2.0,NaN
2,VAST.L,NaN,gb_market,0.116,0.1113 - 0.1198,NaN,24708580,NaN,<built-in method format of str object at 0x7f8...,-0.600000,220674834,0.098 - 0.29,NaN
3,002002.SZ,NaN,cn_market,3.510,3.34 - 3.57,12.4468,9627473920,0.0178042,<built-in method format of str object at 0x7f8...,-0.377660,105661097,2.73 - 5.64,NaN
4,UJO.L,NaN,gb_market,0.160,0.155 - 0.1687,NaN,31705438,NaN,<built-in method format of str object at 0x7f8...,-0.500000,201772895,0.075 - 0.32,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,CMS.DE,NaN,de_market,18.900,18.9 - 18.9,8.76217,2331598336,0.0253968,<built-in method format of str object at 0x7f8...,0.000000,0,10.155 - 18.9,NaN
22,6RS.SG,NaN,dr_market,27.400,27.4 - 27.4,20.3415,2119129600,NaN,<built-in method format of str object at 0x7f8...,-0.297436,0,21.8 - 39.0,NaN
23,TZ6.SG,NaN,dr_market,11.200,11.2 - 11.2,NaN,6680766464,NaN,<built-in method format of str object at 0x7f8...,-0.017544,0,6.0 - 11.4,NaN
24,KSD.F,NaN,dr_market,11.666,11.666 - 11.666,NaN,2517662976,NaN,<built-in method format of str object at 0x7f8...,-0.400034,0,10.2 - 19.44444,NaN
0,DPR.F,NaN,dr_market,16.500,16.5 - 16.5,71.1207,2796106240,0.0059375,<built-in method format of str object at 0x7f8...,0.000000,0,10.5 - 16.5,NaN

In [111]:
newdata['52 Week Low Price Range Change'].map("{:.2%}".format)

TypeError: unsupported format string passed to builtin_function_or_method.__format__

In [82]:
newdata.Country.unique()

array(['us_market', 'gb_market', 'cn_market', 'jp_market', 'de_market',
       'fr_market', 'dr_market'], dtype=object)

In [79]:
#Then I changed the column names so that they become more comprehensible
newdata = newdata.rename(columns={'regularMarketPrice': 'Market Price'})

## Transfering to Mysql
so I created a new database called yahoo_finance in dbeaver

In [57]:
import pymysql
from sqlalchemy import create_engine
from getpass import getpass

In [59]:
username='root'
server='localhost'
database='ironhack'
password=getpass()

engine=create_engine(f'mysql+pymysql://{username}:{password}@{server}/yahoo_finance')

········

In [ ]:
#transfering the dataframe and giving it a name yahoo_finance_sql

In [83]:
newdata.to_sql('yahoo_finance_sql', con=engine,index=False,if_exists='append')

In [84]:
newdata.to_csv(r'/Users/teahupoo20/Documents/GitHub/data-ft-par-labs/Projects/Week-3/newdata.csv')